// Generated by   : ImageConverter Mono Online
// Generated from : akb.png
// Time generated : Wed, 18 Jan 17 11:27:44 +0100  (Server timezone: CET)
// Image Size     : 18x15 pixels
// Memory usage   : 33.75 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
    #define imagedatatype const uint8_t
#elif defined(__PIC32MX__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#elif defined(__arm__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#endif

imagedatatype akb[] PROGMEM={
0xFC, 0x04, 0x04, 0x05, 0x05, 0x05, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x85, 0x05, 0x05, 0x04,   // 0x0010 (16) pixels
0x04, 0xFC, 0xFF, 0xC0, 0xC0, 0xC1, 0xC1, 0xC1, 0xC1, 0xC0, 0xC0, 0xC0, 0xC0, 0xC1, 0xC3, 0xC1,   // 0x0020 (32) pixels
0xC0, 0xC0, 0xC0, 0xFF, 
};
